name: sadl2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch=1.7.1
  - torchaudio=0.7.2
  - torchvision=0.8.2
  - cudatoolkit=11.0.3
  - tensorboard=2.4.1
  - tensorflow=2.3.0
  - tensorflow-gpu=2.3.0
  - tqdm=4.56.2
  - scikit-learn=0.24.1
  - matplotlib=3.3.4
  - keras=2.4.3
